/**
 * HackZurich'18 Vertec 4.0
 * API for the HackZurich'18 Vertec 4.0 Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import io.swagger.client.model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Project".equalsIgnoreCase(className)) {
      return new TypeToken<List<Project>>(){}.getType();
    }
    
    if ("ProjectState".equalsIgnoreCase(className)) {
      return new TypeToken<List<ProjectState>>(){}.getType();
    }
    
    if ("Task".equalsIgnoreCase(className)) {
      return new TypeToken<List<Task>>(){}.getType();
    }
    
    if ("TaskState".equalsIgnoreCase(className)) {
      return new TypeToken<List<TaskState>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Project".equalsIgnoreCase(className)) {
      return new TypeToken<Project>(){}.getType();
    }
    
    if ("ProjectState".equalsIgnoreCase(className)) {
      return new TypeToken<ProjectState>(){}.getType();
    }
    
    if ("Task".equalsIgnoreCase(className)) {
      return new TypeToken<Task>(){}.getType();
    }
    
    if ("TaskState".equalsIgnoreCase(className)) {
      return new TypeToken<TaskState>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
