/*
 * HackZurich'18 Vertec 4.0
 * API for the HackZurich'18 Vertec 4.0 Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Project;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectApi
 */
@Ignore
public class ProjectApiTest {

    private final ProjectApi api = new ProjectApi();

    
    /**
     * Add a new project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProjectTest() throws ApiException {
        Project body = null;
        api.createProject(body);

        // TODO: test validations
    }
    
    /**
     * Deletes a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProjectTest() throws ApiException {
        String projectId = null;
        api.deleteProject(projectId);

        // TODO: test validations
    }
    
    /**
     * Find project by ID
     *
     * Returns a single project
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProjectByIdTest() throws ApiException {
        String projectId = null;
        Project response = api.getProjectById(projectId);

        // TODO: test validations
    }
    
    /**
     * Finds all the projects
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void readProjectsTest() throws ApiException {
        List<Project> response = api.readProjects();

        // TODO: test validations
    }
    
    /**
     * Updates a project
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProjectTest() throws ApiException {
        String projectId = null;
        Project body = null;
        api.updateProject(projectId, body);

        // TODO: test validations
    }
    
}
