/**
 * HackZurich'18 Vertec 4.0
 * API for the HackZurich'18 Vertec 4.0 Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TaskState {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("task_id")
  private Long taskId = null;
  @SerializedName("actual")
  private Long actual = null;
  @SerializedName("number_of_events")
  private Long numberOfEvents = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTaskId() {
    return taskId;
  }
  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getActual() {
    return actual;
  }
  public void setActual(Long actual) {
    this.actual = actual;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getNumberOfEvents() {
    return numberOfEvents;
  }
  public void setNumberOfEvents(Long numberOfEvents) {
    this.numberOfEvents = numberOfEvents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskState taskState = (TaskState) o;
    return (this.id == null ? taskState.id == null : this.id.equals(taskState.id)) &&
        (this.taskId == null ? taskState.taskId == null : this.taskId.equals(taskState.taskId)) &&
        (this.actual == null ? taskState.actual == null : this.actual.equals(taskState.actual)) &&
        (this.numberOfEvents == null ? taskState.numberOfEvents == null : this.numberOfEvents.equals(taskState.numberOfEvents));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.taskId == null ? 0: this.taskId.hashCode());
    result = 31 * result + (this.actual == null ? 0: this.actual.hashCode());
    result = 31 * result + (this.numberOfEvents == null ? 0: this.numberOfEvents.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskState {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  taskId: ").append(taskId).append("\n");
    sb.append("  actual: ").append(actual).append("\n");
    sb.append("  numberOfEvents: ").append(numberOfEvents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
