/*
 * HackZurich'18 Vertec 4.0
 * API for the HackZurich'18 Vertec 4.0 Project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ProjectState
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-15T10:27:27.424+02:00")
public class ProjectState {
  @SerializedName("_id")
  private String id = null;

  @SerializedName("project_id")
  private String projectId = null;

  @SerializedName("actual")
  private Long actual = null;

  @SerializedName("number_of_tasks")
  private Long numberOfTasks = null;

  public ProjectState id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProjectState projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @ApiModelProperty(value = "")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public ProjectState actual(Long actual) {
    this.actual = actual;
    return this;
  }

   /**
   * Get actual
   * @return actual
  **/
  @ApiModelProperty(value = "")
  public Long getActual() {
    return actual;
  }

  public void setActual(Long actual) {
    this.actual = actual;
  }

  public ProjectState numberOfTasks(Long numberOfTasks) {
    this.numberOfTasks = numberOfTasks;
    return this;
  }

   /**
   * Get numberOfTasks
   * @return numberOfTasks
  **/
  @ApiModelProperty(value = "")
  public Long getNumberOfTasks() {
    return numberOfTasks;
  }

  public void setNumberOfTasks(Long numberOfTasks) {
    this.numberOfTasks = numberOfTasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectState projectState = (ProjectState) o;
    return Objects.equals(this.id, projectState.id) &&
        Objects.equals(this.projectId, projectState.projectId) &&
        Objects.equals(this.actual, projectState.actual) &&
        Objects.equals(this.numberOfTasks, projectState.numberOfTasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, actual, numberOfTasks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectState {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    actual: ").append(toIndentedString(actual)).append("\n");
    sb.append("    numberOfTasks: ").append(toIndentedString(numberOfTasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

